version: '3.8'

services:
  # --- INFRASTRUCTURE ---
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - elasticnet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: elasticsearch
    ports:
      - '9200:9200'
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xmx512m -Xms512m
    volumes:
      - ./elastic/data:/usr/share/elasticsearch/data
    networks:
      - elasticnet

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    container_name: kibana
    ports:
      - '5601:5601'
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elasticnet


  bitcask-server:
    image: muhammedatef14/bitcask-server:latest
    container_name: bitcask-server
    ports:
      - "50051:50051"
    volumes:
      - bitcask_data:/data/bitcask
    restart: unless-stopped
    networks:
      - elasticnet


  central-station:
    image: muhammedatef14/central-station:latest
    container_name: central-station
    depends_on:
      - kafka
      - bitcask-server
    environment:
      - KAFKA_BROKER=kafka:29092
      - BITCASK_DIR=/data/bitcask
      - PARQUET_DIR=/data/parquet
    volumes:
      - ./parquet-data:/data/parquet
      - ./bitcask-data:/data/bitcask
    networks:
      - elasticnet

  weather-station-1:
    image: muhammedatef14/weather-station:latest
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:29092
      - STATION_ID=1
      - MAIN_CLASS=com.data_aquisition.producer.WeatherStationProducer
    networks:
      - elasticnet


  weather-station-2:
    image: muhammedatef14/weather-station:latest
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:29092
      - STATION_ID=2
      - MAIN_CLASS=com.data_aquisition.producer.WeatherStationProducer
    networks:
      - elasticnet

  weather-station-3:
    image: muhammedatef14/weather-station:latest
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:29092
      - STATION_ID=3
      - MAIN_CLASS=com.data_aquisition.producer.WeatherStationProducer
    networks:
      - elasticnet



  weather-station-api:
    image: muhammedatef14/meteo-api-station:latest
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:29092
      - MAIN_CLASS=com.data_aquisition.producer.OpenMeteoChannelAdaptor
    networks:
      - elasticnet

  es-worker:
    image: muhammedatef14/es-worker:latest
    container_name: es-worker
    depends_on:
      - elasticsearch
      - central-station
    environment:
      - ES_URL=http://elasticsearch:9200/_bulk
      - PARQUET_DIR=/data/parquet
    volumes:
      - ./parquet-data:/data/parquet
    networks:
      - elasticnet

# --- NETWORKS & VOLUMES ---
networks:
  elasticnet:
    driver: bridge

volumes:
  bitcask_data:
  logvolume01: