# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bitcask.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbitcask.proto\"\x07\n\x05\x45mpty\"\x1e\n\nKeyRequest\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\";\n\rValueResponse\x12\x14\n\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n\x05\x66ound\x18\x02 \x01(\x08R\x05\x66ound\"6\n\x0cKeyValuePair\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value\"4\n\rKeyValueChunk\x12#\n\x05pairs\x18\x01 \x03(\x0b\x32\r.KeyValuePairR\x05pairs\"4\n\nPutRequest\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value\"A\n\x0bPutResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\x12\x18\n\x07message\x18\x02 \x01(\tR\x07message\"C\n\rMergeResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\x12\x18\n\x07message\x18\x02 \x01(\tR\x07message2\xa2\x01\n\x0e\x42itcaskService\x12&\n\nGetAllKeys\x12\x06.Empty\x1a\x0e.KeyValueChunk0\x01\x12%\n\x06GetKey\x12\x0b.KeyRequest\x1a\x0e.ValueResponse\x12 \n\x03Put\x12\x0b.PutRequest\x1a\x0c.PutResponse\x12\x1f\n\x05Merge\x12\x06.Empty\x1a\x0e.MergeResponseB\'\n\x15\x63om.ddia.bitcask.grpcB\x0c\x42itcaskProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bitcask_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.ddia.bitcask.grpcB\014BitcaskProtoP\001'
  _globals['_EMPTY']._serialized_start=17
  _globals['_EMPTY']._serialized_end=24
  _globals['_KEYREQUEST']._serialized_start=26
  _globals['_KEYREQUEST']._serialized_end=56
  _globals['_VALUERESPONSE']._serialized_start=58
  _globals['_VALUERESPONSE']._serialized_end=117
  _globals['_KEYVALUEPAIR']._serialized_start=119
  _globals['_KEYVALUEPAIR']._serialized_end=173
  _globals['_KEYVALUECHUNK']._serialized_start=175
  _globals['_KEYVALUECHUNK']._serialized_end=227
  _globals['_PUTREQUEST']._serialized_start=229
  _globals['_PUTREQUEST']._serialized_end=281
  _globals['_PUTRESPONSE']._serialized_start=283
  _globals['_PUTRESPONSE']._serialized_end=348
  _globals['_MERGERESPONSE']._serialized_start=350
  _globals['_MERGERESPONSE']._serialized_end=417
  _globals['_BITCASKSERVICE']._serialized_start=420
  _globals['_BITCASKSERVICE']._serialized_end=582
# @@protoc_insertion_point(module_scope)
