# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import bitcask_pb2 as bitcask__pb2


class BitcaskServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllKeys = channel.unary_stream(
                '/BitcaskService/GetAllKeys',
                request_serializer=bitcask__pb2.Empty.SerializeToString,
                response_deserializer=bitcask__pb2.KeyValueChunk.FromString,
                )
        self.GetKey = channel.unary_unary(
                '/BitcaskService/GetKey',
                request_serializer=bitcask__pb2.KeyRequest.SerializeToString,
                response_deserializer=bitcask__pb2.ValueResponse.FromString,
                )
        self.Put = channel.unary_unary(
                '/BitcaskService/Put',
                request_serializer=bitcask__pb2.PutRequest.SerializeToString,
                response_deserializer=bitcask__pb2.PutResponse.FromString,
                )
        self.Merge = channel.unary_unary(
                '/BitcaskService/Merge',
                request_serializer=bitcask__pb2.Empty.SerializeToString,
                response_deserializer=bitcask__pb2.MergeResponse.FromString,
                )


class BitcaskServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Merge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BitcaskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllKeys': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAllKeys,
                    request_deserializer=bitcask__pb2.Empty.FromString,
                    response_serializer=bitcask__pb2.KeyValueChunk.SerializeToString,
            ),
            'GetKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKey,
                    request_deserializer=bitcask__pb2.KeyRequest.FromString,
                    response_serializer=bitcask__pb2.ValueResponse.SerializeToString,
            ),
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=bitcask__pb2.PutRequest.FromString,
                    response_serializer=bitcask__pb2.PutResponse.SerializeToString,
            ),
            'Merge': grpc.unary_unary_rpc_method_handler(
                    servicer.Merge,
                    request_deserializer=bitcask__pb2.Empty.FromString,
                    response_serializer=bitcask__pb2.MergeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BitcaskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BitcaskService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/BitcaskService/GetAllKeys',
            bitcask__pb2.Empty.SerializeToString,
            bitcask__pb2.KeyValueChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BitcaskService/GetKey',
            bitcask__pb2.KeyRequest.SerializeToString,
            bitcask__pb2.ValueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BitcaskService/Put',
            bitcask__pb2.PutRequest.SerializeToString,
            bitcask__pb2.PutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Merge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BitcaskService/Merge',
            bitcask__pb2.Empty.SerializeToString,
            bitcask__pb2.MergeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
