apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: weather-station
spec:
  serviceName: "weather-station"
  replicas: 10
  selector:
    matchLabels:
      app: weather-station
  template:
    metadata:
      labels:
        app: weather-station
    spec:
      containers:
        - name: weather-station
          image: muhammedatef14/weather-station:v3  # We will build v3 next!
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKER
              value: "kafka:29092"
            - name: MAIN_CLASS
              value: "com.data_aquisition.producer.WeatherStationProducer"
            - name: STATION_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name